name: Loop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: commit
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --local user.email "amirhamzan3@gmail.com"
        git config --local user.name "budak4"
        date > date
        git add -A
        git commit -m "Looping..." -a
        git push "https://github.com/budak4/WORKFLOWTEST.git" HEAD:master --follow-tags
